### ISSUE TITLE
Reflect specific lauren changes to chapter 3 flow

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graph-stats-book#61]
update figures

delete section 1 and move adj mtx stuff to section 2
move the rest to regularization of the edges
separate regularization into regularization of nodes and edges (separate)
put "intro to causal inference" in the main content, and put "bag of features" limitations there
put "bag of nodes and networks" in the "next" section or chapter 5

**Comment by loftusa** [comment]
- [x] delete section 1 and move adj mtx stuff to section 2
- [x] move the rest to regularization of the edges
- [x] separate regularization into regularization of nodes and edges (separate)
- [ ] put "intro to causal inference" in the main content, and put "bag of features" limitations there
- [ ] put "bag of nodes and networks" in the "next" section or chapter 5

**Comment by loftusa** [comment]
I've done some reorganization, but it wasn't these (I reflected her comments that were inside the PDF). I have:

- [x] moved the adjacency matrix stuff to the beginning
- [x] reorganized the degree matrix stuff
- [x] moved around paragraphs that she wanted to be opening sections to be opening sections
- [x] turned `Network summary statistics tell you useful attributes about networks` into its own section

I didn't move the degree matrix stuff to ch2, because we have the parts in the degree matrix explaining weightedness and directedness, and we don't introduce those until a bit later. If you or lauren feels strongly about it, I guess we can do a bigger reorganization to account for that? But my personally opinion is that that'd add a bit too much entropy to the structure.

**Comment by loftusa** [comment]
done with all this stuff, remaining checkmarks we're not doing
