### ISSUE TITLE
Read pages 436 - 440

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graph-stats-book#64]
Textbook pages (top left page counter of the book), not pdf document pages. Added description of skip-gram model

**Comment by loftusa** [comment]
on this now

**Comment by ebridge2** [comment]
I left a comment around line 351 for u

**Comment by loftusa** [comment]
@ebridge2 I read through this. it's incomplete, e.g., no python code, but other than that seems perfectly fine. I added an explanation of cross-entropy and some other minor changes. 

it'd be cool to implement node2vec in pytorch/pytorch-lightning/fastai for the book, but maybe not worth it since we're low on time.

**Comment by loftusa** [comment]
i'll leave this issue open for the moment since the section is incomplete, but un-assigning myself and assigning you
