### ISSUE TITLE
summary table at the end of chapter 4

### ISSUE THREAD

**Issue by loftusa** [neurodata/graph-stats-book#66]
Lauren: You introduce so many models in this chapter that I began to get lost after a while. Is it possible to include a summary table at the end listing each model, what its distinctive features are, and when we might use it?

**Comment by ebridge2** [comment]
@loftusa check 4.8. Close if you think I addressed sufficiently. Only included single network models because I think the others are pretty self-contained (e.g., the other network models are very different in how they are specified, and we rarely are concerned with their interrelations). We could also just move it to the end entirely and just exhaustively list them, but I'm skeptical there's much benefit for some of the others (SSNs, COSIE, JRDPG, SIEM).
