### ISSUE TITLE
Make sure we talk about edge graphs somewhere

### ISSUE THREAD

**Issue by loftusa** [neurodata/graph-stats-book#77]
I'm not actually sure if we have a section anywhere mentioning edge graphs, but if we don't we definitely need it since the value is so high

So, check to make sure that section exists. If it doesn't, write it.

(e.g., 'remember all those things we can learn about nodes? well we can learn all of the exact same things about edges too, just by inverting the graph!)

**Comment by ebridge2** [comment]
Step 1: Ascertain that this is relevant. 

Alex: "you can make an edge graph, and then run these things on them." Eric: "is that useful to do within the confines of the frameworks that we discuss in the book, or orthogonal?"

What happens when you do ase(edgegraphify(SBM)), and ase(edgegraphify(SIEM)), where the SIEM has a "diagonalized" block structure (e.g., every node has a corresponding pair with very high edge probability, and a much lower edge probability outside of their pair

**Comment by ebridge2** [comment]
Following are the projected outcomes, and the possible paths:

1) It works within the frameworks described (doing spectral techniques to edgegraphs for statistical models does useful things): it is <3 paragraphs.
2) It does not work within the frameworks described:
    a. it is not something people use a lot: disregard, and dont bring up.
    b. it is something people use a lot: extended discussion in Ch9 (3-4 pages?) where the extra 3 pages on top of the ~3 paragraphs contextify it.
