### ISSUE TITLE
Code reproduction

### ISSUE THREAD

**Issue by ebridge2** [neurodata/graph-stats-book#99]
- [x] https://github.com/neurodata/graph-stats-book/issues/98
- [x] https://github.com/neurodata/graph-stats-book/issues/97

These should be done iteratively, and probably in tandem.

**Comment by loftusa** [comment]
figures

- ch2/discover-and-visualize.tex fig:ch2:brain_preds replaced figure, double check its good
- ch2/discover-and-visualize.tex line 98 I got a slightly different confusion matrix
- ch2/fine-tune.tex figure not exactly the same, even with random seeds
- ch2/select-and-train.tex replaced with the one I generated
- ch4 changed a lot of the notebook code organization so that puts images to axes properly
- ch4/properties-of-networks.tex (A) needs a title
- ch5/indef_blockmatrix line 318 (B) B has different colorbar ticks (in notebook, it goes 0, 0.5, 1.0)
- same thing in ch5/dcsbm C) has different yaxis labels than notebooks
- ch6/lse fig:ch6:lse:dcsbm_ase needs dimension labels (fixed in notebooks)
- **ch6/multigraph.tex fig:ch6:multinet:comb_{sep, emb} are not in the notebooks**
- ch7/sparsity.tex fig:ch7:density:sparsity is different in the text vs notebook
- ch8/twosamplesbm.tex fig:ch8:twosampsbm:pval_mtx (A) and (B) dont appear to coincide with each other, and is not reproduced by book figure code
- ch8/gm.tex there are illustrator-based figures that don't exist in the figure code
- ch9 GNNs: most of the figures are illustrator and therefore not python-reproducible. The end of the .ipynb has a bunch of plotting code that doesn't generate any plots.
**- ch9 random walks: fig:next:embed doesnt reproduce properly. There does not appear to be community structure in the notebook.**

**Comment by loftusa** [comment]
@ebridge2 can you work on the above while I do readthrough?

**Comment by ebridge2** [comment]
I already looked at them and made tweaks to fixable stuff. I dont understand some of the comments though so will discuss as we go

**Comment by ebridge2** [comment]
Node2vec... argh

**Comment by ebridge2** [comment]
Closing and replacing with #108 which seems to be only outstanding problem
